[package]
name = "test_double"
version = "0.1.0"
authors = ["Jason Grlicky <jason@paracosm.us>"]
description = "Procedural macro for substituting one type for another when testing."
keywords = ["mock", "test", "testing", "TDD"]
categories = ["development-tools::testing"]
readme = "README.md"
repository = "https://github.com/pcsm/test_double"
license = "MIT OR Apache-2.0"

[badges]
maintenance = { status = "experimental" }

[dependencies]
syn = { version = "0.12", features = ["full"] }
quote = "0.4"
proc-macro2 = "0.2"

[lib]
proc-macro = true